# Generated by Django 2.2.3 on 2019-07-03 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0002_auto_20190702_1252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Observer',
            new_name='Buddy',
        ),
        migrations.AddField(
            model_name='habit',
            name='buddy',
            field=models.ManyToManyField(related_name='buddy', to=settings.AUTH_USER_MODEL),
        ),
    ]
