# Generated by Django 2.2.3 on 2019-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_auto_20190703_0909'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailyrecord',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='user'),
        ),
    ]
