# Generated by Django 2.2.3 on 2019-07-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_auto_20190703_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buddy',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
