# Generated by Django 2.2.3 on 2019-07-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
