# Generated by Django 2.2.3 on 2019-07-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_auto_20190703_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='target_book',
            new_name='target_record',
        ),
    ]
